# MUSUBI Project Configuration
name: TENJIN
description: 教育理論GraphRAG MCPサーバー - esperantoによるマルチLLM統合
locale: ja
version: "0.2.1-dev"
created: 2025-12-26
updated: 2025-12-28

# Technology Stack
tech_stack:
  approach: clean-architecture-mcp
  languages:
    - python
    - javascript
  primary_language: python
  python_version: "3.11+"
  frameworks:
    - fastmcp
    - esperanto
    - pydantic
  databases:
    - neo4j
    - chromadb
  testing:
    - pytest
    - pytest-asyncio
  tools:
    - ruff
    - mypy
    - docker-compose

# Project Type
project_type: mcp-server
domain: education-technology

# Dependencies
dependencies:
  llm_integration: esperanto
  mcp_framework: fastmcp
  graph_db: neo4j
  vector_db: chromadb
  validation: pydantic

# Sub-Projects
sub_projects:
  theory_editor:
    path: ./tools/theory-editor
    description: 教育理論データエディター（Web GUI）
    tech_stack:
      - vanilla-javascript
      - html5
      - css3
    status: completed
    specs:
      requirements: ./storage/specs/REQ-002-theory-editor.md
      design: ./storage/specs/DESIGN-002-theory-editor.md
      tasks: ./storage/specs/TASKS-002-theory-editor.md
    docs:
      readme: ./tools/theory-editor/README.md
      api: ./tools/theory-editor/docs/API.md
      architecture: ./tools/theory-editor/docs/ARCHITECTURE.md

# MCP Server Integration
mcp_integration:
  config_file: ./.vscode/mcp.json
  embedding_provider: ollama
  embedding_model: bge-m3  # 多言語対応（100+言語）
  embedding_dimensions: 1024
  ollama_host: http://192.168.224.1:11434
  neo4j_url: bolt://localhost:7687
  theories_loaded: 175
  llm_model: qwen2.5:7b
  llm_provider: ollama

# References (not tracked in git)
references:
  tengin_graphrag: ./References/TENGIN-GraphRAG  # Local only, not pushed
  mcp_spec: https://modelcontextprotocol.io/
  esperanto: https://github.com/lfnovo/esperanto

# Current Sprint
current_sprint:
  feature: multilingual-search-enhancement
  phase: completed
  started: 2025-12-28
  last_updated: 2025-12-28
  milestones:
    - name: bge-m3 Multilingual Embedding Migration
      status: completed
      description: 多言語エンベディングモデルへの移行（日本語検索精度向上）
      changes:
        - embedding model: nomic-embed-text → bge-m3
        - embedding dimensions: 768 → 1024
        - languages supported: 100+
    - name: esperanto API Compatibility Fixes
      status: completed
      changes:
        - Provider class direct usage (OllamaLanguageModel, OpenAILanguageModel)
        - LLM method: chat_async → achat_complete
        - Settings .env loading fix
        - Neo4j Cypher: length() → size()
        - VectorRepository: search → semantic_search
        - SearchResult: entity_id → id, relevance_score → score
    - name: Test Updates
      status: completed
      tests_passed:
        unit: 18
        e2e_theory_editor: 14
        e2e_mcp_server: 10
        total: 42
    - name: Documentation Updates
      status: completed
      updated_files:
        - CHANGELOG.md
        - README.md

# Completed Sprints Archive
completed_sprints:
  - feature: multilingual-search-enhancement
    phase: completed
    started: 2025-12-28
    completed: 2025-12-28
    key_changes:
      - bge-m3 multilingual embedding model
      - esperanto API compatibility fixes
      - 42 tests passing (18 unit + 14 e2e + 10 mcp)
  - feature: mcp-integration-complete
    phase: completed
    started: 2025-12-27
    completed: 2025-12-27
    key_changes:
      - GraphRAG implementation
      - Theory Editor
      - MCP Server VS Code integration
  - feature: theory-editor
    phase: completed
    tasks_completed: 16
    tasks_total: 16
    started: 2025-12-27
    completed: 2025-12-27
    completed_tasks:
      - TASK-001 to TASK-016 (all completed)
