# MUSUBI Project Configuration
name: TENJIN
description: 教育理論GraphRAG MCPサーバー - esperantoによるマルチLLM統合
locale: ja
version: "0.2.2-dev"
created: 2025-12-26
updated: 2025-12-28

# Technology Stack
tech_stack:
  approach: clean-architecture-mcp
  languages:
    - python
    - javascript
  primary_language: python
  python_version: "3.11+"
  frameworks:
    - fastmcp
    - esperanto
    - pydantic
    - starlette
  databases:
    - neo4j
    - chromadb
    - redis
  testing:
    - pytest
    - pytest-asyncio
  tools:
    - ruff
    - mypy
    - docker-compose

# Project Type
project_type: mcp-server
domain: education-technology

# Dependencies
dependencies:
  llm_integration: esperanto
  mcp_framework: fastmcp
  graph_db: neo4j
  vector_db: chromadb
  validation: pydantic

# Sub-Projects
sub_projects:
  theory_editor:
    path: ./tools/theory-editor
    description: 教育理論データエディター（Web GUI）
    tech_stack:
      - vanilla-javascript
      - html5
      - css3
    status: completed
    specs:
      requirements: ./storage/specs/REQ-002-theory-editor.md
      design: ./storage/specs/DESIGN-002-theory-editor.md
      tasks: ./storage/specs/TASKS-002-theory-editor.md
    docs:
      readme: ./tools/theory-editor/README.md
      api: ./tools/theory-editor/docs/API.md
      architecture: ./tools/theory-editor/docs/ARCHITECTURE.md

# MCP Server Integration
mcp_integration:
  config_file: ./.vscode/mcp.json
  embedding_provider: ollama
  embedding_model: bge-m3  # 多言語対応（100+言語）
  embedding_dimensions: 1024
  ollama_host: http://192.168.224.1:11434
  neo4j_url: bolt://localhost:7687
  theories_loaded: 175
  llm_model: qwen2.5:7b
  llm_provider: ollama

# References (not tracked in git)
references:
  tengin_graphrag: ./References/TENGIN-GraphRAG  # Local only, not pushed
  mcp_spec: https://modelcontextprotocol.io/
  esperanto: https://github.com/lfnovo/esperanto

# Current Sprint
current_sprint:
  feature: v0.2.2-advanced-features
  phase: in-progress
  started: 2025-12-28
  last_updated: 2025-12-28
  milestones:
    - name: synthesize_theories Tool
      status: completed
      description: 複数理論の統合分析・比較ツール
      changes:
        - InferenceService.synthesize_theories()
        - 統合フレームワーク生成
        - シナジー/緊張関係分析
    - name: batch_search API
      status: completed
      description: 複数クエリの一括検索
      changes:
        - SearchService.batch_search()
        - 並列実行
        - 共通理論の抽出
    - name: Theory Editor WebSocket
      status: completed
      description: リアルタイム同期機能
      changes:
        - ws-sync-server.py (Starlette WebSocket)
        - graphrag-sync.js WebSocketクライアント
        - 接続状態インジケーターUI
    - name: Search Filter Extension
      status: completed
      description: 年代・エビデンスレベルフィルター
      changes:
        - year_from/year_to パラメータ
        - decade フィルター (e.g., "1990s")
        - evidence_level フィルター
    - name: Export Functionality
      status: completed
      description: JSON/Markdown/CSVエクスポート
      changes:
        - ExportService
        - export_theories_json tool
        - export_theories_markdown tool
        - export_theories_csv tool

# Completed Sprints Archive
completed_sprints:
  - feature: v0.2.1-multilingual-enhancement
    phase: completed
    started: 2025-12-28
    completed: 2025-12-28
    key_changes:
      - bge-m3 multilingual embedding model
      - esperanto API compatibility fixes
      - SSE transport support
      - Redis cache integration
      - 42 tests passing (18 unit + 14 e2e + 10 mcp)
  - feature: multilingual-search-enhancement
    phase: completed
    started: 2025-12-28
    completed: 2025-12-28
    key_changes:
      - bge-m3 multilingual embedding model
      - esperanto API compatibility fixes
      - 42 tests passing (18 unit + 14 e2e + 10 mcp)
  - feature: mcp-integration-complete
    phase: completed
    started: 2025-12-27
    completed: 2025-12-27
    key_changes:
      - GraphRAG implementation
      - Theory Editor
      - MCP Server VS Code integration
  - feature: theory-editor
    phase: completed
    tasks_completed: 16
    tasks_total: 16
    started: 2025-12-27
    completed: 2025-12-27
    completed_tasks:
      - TASK-001 to TASK-016 (all completed)
